### ISSUE TITLE
wrpclient.readthedocs.io has missing API docs

### ISSUE THREAD

**Issue by hroncok** [Kasape/wrp-client#1]
See for example https://wrpclient.readthedocs.io/en/latest/classes/camera.html

![_](https://user-images.githubusercontent.com/2401856/73643717-49692680-4674-11ea-84c3-4f789aa7a3e8.png)

This usually means readthedocs has some missing deps or bad `sys.path` (not seeing your code). Locally generated documentation works fine.

**Comment by Kasape** [comment]
Fixed by checking the `Install Project` checkbox in RTD Admin panel
